<?php
/*******************************************************************************
 *   copyright				: (C) 2014 - 2018 Pro-Auction-Script
 *   site					: https://www.pro-auction-script.com
 *   Script License			: https://www.pro-auction-script.com/contents.php?show=free_license
 *******************************************************************************/

if (!defined('InProAuctionScript')) exit('Access denied');

$carriers = array(
	'@sms.airfiremobile.com' => 'Airfire Mobile',
	'@msg.acsalaska.com' => 'Alaska Communications',
	'@sms.alltelwireless.com' => 'Alltel (Allied Wireless)',
	'@paging.acswireless.com' => 'Ameritech',
	'@vmobl.com' => 'Assurance Wireless',
	'@txt.att.net' => 'AT&T',
	'@page.att.net' => 'AT&T Enterprise Paging',
	'@sms.smartmessagingsuite.com' => 'AT&T Global Smart Messaging Suite',
	'@cingularme.com' => 'AT&T Mobility (formerly Cingular)',
	'@bellsouth.cl' => 'BellSouth',
	'@sms.bluecell.com' => 'Bluegrass Cellular',
	'@sms.myboostmobile.com' => 'Boost Mobile',
	'@cbeyond.sprintpcs.com' => 'C Beyond (All Page Wireless)',
	'@cspire1.com' => 'C Spire Wireless',
	'@cellcom.quiktxt.com' => 'Cellcom',
	'@csouth1.com' => 'Cellular South',
	'@sms.cvalley.net' => 'Chariton Valley Wireless',
	'@mail.msgsender.com' => 'Chat Mobility',
	'@mms.gocbw.com' => 'Cincinnati Bell',
	'@mobile.mycingular.com' => 'Cingular (Postpaid)',
	'@sms.cleartalk.us' => 'Cleartalk',
	'@mms.cricketwireless.net' => 'Cricket',
	'@sms.advantagecell.net' => 'DTC',
	'@sms.edgewireless.com' => 'Edge Wireless',
	'@SMS.elementmobile.net' => 'Element Mobile',
	'@echoemail.net' => 'Esendex',
	'@iwirelesshometext.com' => 'i-wireless (Sprint PCS)',
	'@mobile.kajeet.net' => 'Kajeet',
	'@text.longlines.com' => 'LongLines',
	'@mymetropcs.com' => 'MetroPCS',
	'@sms.ntwls.net' => 'Nextech',
	'@vtext.com' => 'Page Plus Cellular(Verizon MVNO)',
	'@zsend.com' => 'Pioneer Cellular',
	'@qwestmp.com' => 'Qwest Wireless',
	'@smtext.com' => 'Simple Mobile',
	'@page.southernlinc.com' => 'Southernlinc',
	'@pm.sprint.com' => 'Sprint',
	'@messaging.sprintpcs.com' => 'Straight Talk',
	'@rinasms.com' => 'Syringa Wireless',
	'@teleflip.com' => 'Teleflip',
	'@message.ting.com' => 'Ting',
	'@tmomail.net' => 'T-mobile',
	'@utext.com' => 'Unicel',
	'@union-tel.com' => 'Union Wireless',
	'@email.uscc.net' => 'US Cellular',
	'@usamobility.net' => 'USA Mobility',
	'@vzwpix.com' => 'Verizon Wireless',
	'@text.wireless.alltel.com' => 'Verizon Wireless (Alltel)',
	'@vmpix.com' => 'Virgin Mobile',
	'@text.voyagermobile.com' => 'Voyager Mobile',
	'@sms.wcc.net' => 'West Central Wireless',
	'@mobile.gci.net' => 'General Communications Inc.',
	'@psms.bluesky.as' => 'Bluesky Communications',
	'@gscsms.com' => 'Golden State Cellular',
	'@vtxt.com' => 'Greatcall',
	'@gocbw.com' => 'Cincinnati Bell',
	'@hawaii.sprintpcs.com' => 'Hawaiian Telcom Wireless',
	'@iwspcs.net' => 'i wireless (T-Mobile)',
	'@sms.pocket.com' => 'Pocket Wireless',
	'@sms.xit.net' => 'XIT Communications',
	'@pcs.ntelos.com' => 'nTelos',
	'@cwemail.com' => 'Centennial Wireless'
);